language: rust
sudo: required
dist: trusty
services: docker
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo

matrix:
  include:
    - name: "[RELEASE + DEBUG]: Tests w. sanitizers"
      rust: nightly
      script:
        - cargo clean
        # Debug:
        # Sanitizers with default features
        - RUSTFLAGS="-Z sanitizer=address" ASAN_OPTIONS="detect_odr_violation=0" cargo test --tests --target x86_64-unknown-linux-gnu
        - RUSTFLAGS="-Z sanitizer=leak" cargo test --tests --target x86_64-unknown-linux-gnu
        # No default features
        - RUSTFLAGS="-Z sanitizer=address" ASAN_OPTIONS="detect_odr_violation=0" cargo test --no-default-features --tests --target x86_64-unknown-linux-gnu
        - RUSTFLAGS="-Z sanitizer=leak" cargo test --no-default-features --tests --target x86_64-unknown-linux-gnu
        
        # Release:
        # Sanitizers with default features
        - RUSTFLAGS="-Z sanitizer=address" ASAN_OPTIONS="detect_odr_violation=0" cargo test --tests --release --target x86_64-unknown-linux-gnu
        - RUSTFLAGS="-Z sanitizer=leak" cargo test --tests --release --target x86_64-unknown-linux-gnu
        # No default features
        - RUSTFLAGS="-Z sanitizer=address" ASAN_OPTIONS="detect_odr_violation=0" cargo test --no-default-features --tests --release --target x86_64-unknown-linux-gnu
        - RUSTFLAGS="-Z sanitizer=leak" cargo test --no-default-features --tests --release --target x86_64-unknown-linux-gnu

        - cargo clean

    - name: "[RELEASE + DEBUG (stable)]: Build no_std"
      env: TARGET=thumbv7em-none-eabi
      rust: stable
      install:
        - cargo install xargo || true
        - rustup target add $TARGET
        - rustup component add rust-src
      script:
        # Debug:
        - xargo build --no-default-features --verbose --target $TARGET
          
        # Release:
        - xargo build --release --no-default-features --verbose --target $TARGET

    - name: "[RELEASE + DEBUG (nightly)]: Build no_std"
      env: TARGET=thumbv7em-none-eabi
      rust: nightly
      install:
        - cargo install xargo || true
        - rustup target add $TARGET
        - rustup component add rust-src
      script:
        # Debug:
        - xargo build --no-default-features --verbose --target $TARGET
          
        # Release:
        - xargo build --release --no-default-features --verbose --target $TARGET

install:
  - cargo install cross || true
