image: Visual Studio 2017

environment:
  matrix:
    # MSVC Rust stable
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: stable
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: stable
    # MSVC Rust nightly
    - TARGET: i686-pc-windows-msvc
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  - cargo build --target %TARGET%
  - cargo build --target %TARGET% --release
  - cargo test --target %TARGET%
  - cargo test --target %TARGET% --release
  # no_std
  - cargo build --no-default-features --target %TARGET%
  - cargo build --no-default-features --target %TARGET% --release
  - cargo test --tests --no-default-features --target %TARGET%
  - cargo test --tests --no-default-features --target %TARGET% --release

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

# We're already building in test_script
build: false