[package]
name = "orion"
version = "0.11.0"
authors = ["brycx <brycx@protonmail.com>"]
description = "Easy and usable rust crypto"
keywords = [ "cryptography", "hmac", "hkdf", "xchacha20_poly1305", "chacha20_poly1305" ]
categories = [ "cryptography", "no-std" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "benches/*",
    "fuzz/*",
    "tests/*"
]

[dependencies]
rand = { version = "0.6.1", optional = true }
sha2 = { version = "0.8.0", default-features = false }
tiny-keccak = "1.4.2"
byteorder = { version = "1.2.7", default-features = false }
subtle = { version = "2.0.0", default-features = false }
clear_on_drop = "=0.2.3"

[features]
default = [ "safe_api" ]
safe_api = [ "rand" ]
nightly = [ "clear_on_drop/nightly", "subtle/nightly", "safe_api" ]
no_std = [ "clear_on_drop/nightly", "subtle/nightly" ]

[dev-dependencies]
hex = "0.3.2"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 3

[badges]
travis-ci = { repository = "brycx/orion" }
codecov = { repository = "brycx/orion" }
maintenance = { status = "actively-developed" }
