[package]
name = "orion"
version = "0.15.5" # Update html_root_url in lib.rs along with this.
authors = ["brycx <brycx@protonmail.com>"]
description = "Usable, easy and safe pure-Rust crypto"
keywords = [ "cryptography", "crypto", "aead", "hash", "mac" ]
categories = [ "cryptography", "no-std" ]
edition = "2018"
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "tests/*"
]

[dependencies]
subtle = { version = "^2.2.2", default-features = false }
zeroize = { version = "1.1.0", default-features = false }
getrandom = { version = "0.2.0", optional = true }
base64 = { version = "0.13.0", optional = true }

[features]
default = [ "safe_api" ]
safe_api = [ "getrandom", "base64" ]
alloc = []

[dev-dependencies]
hex = "0.4.0"
serde_json = "1.0.41"
serde = { version = "1.0", features = ["derive"] }
quickcheck = "1.0.2"
criterion = "0.3.0"

[[bench]]
name = "bench"
harness = false

[profile.dev]
opt-level = 1

