[package]
name = "orion"
version = "0.14.4" # Update html_root_url in lib.rs along with this.
authors = ["brycx <brycx@protonmail.com>"]
description = "Easy and usable rust crypto"
keywords = [ "cryptography", "crypto", "aead", "hash", "mac" ]
categories = [ "cryptography", "no-std" ]
edition = "2018"
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "benches/*",
    "tests/*"
]

[dependencies]
subtle = { version = "2.1.1", default-features = false }
zeroize = { version = "0.10.1", default-features = false }
getrandom = { version = "0.1.12", optional = true }
bitflags = { version = "1.1.0" }
static_assertions = { version = "1.0.0" }


[features]
default = [ "safe_api" ]
safe_api = [ "getrandom" ]
nightly = [ "subtle/nightly", "safe_api" ]
no_std = [ "subtle/nightly" ]

[dev-dependencies]
hex = "0.3.2"
serde_json = "1.0.40"
quickcheck = "0.9.0"
criterion = "0.3.0"

[[bench]]
name = "bench"
harness = false

[profile.bench]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.release]
opt-level = 3
debug = false
lto = true
debug-assertions = false

[profile.dev]
opt-level = 1

[badges]
travis-ci = { repository = "brycx/orion", branch = "crates-published" }
codecov = { repository = "brycx/orion", branch = "crates-published" }
appveyor = { repository = "brycx/orion", branch = "crates-published" }
maintenance = { status = "actively-developed" }
