[package]
name = "orion"
version = "0.7.4"
authors = ["brycx <brycx@protonmail.com>"]
description = "Easy and usable rust crypto"
keywords = [ "cryptography", "hmac", "hkdf", "pbkdf2", "chacha20" ]
categories = [ "cryptography", "no-std" ]
readme = "README.md"
repository = "https://github.com/brycx/orion"
documentation = "https://docs.rs/orion"
license = "MIT"
exclude = [
    ".gitignore",
    ".travis.yml",
    "benches/*",
    "fuzz/*",
    "tests/*",
    "logo/*"
]

[dependencies]
rand = { version = "0.5.5", optional = true }
sha2 = "0.8.0"
tiny-keccak = "1.4.2"
byteorder = { version = "1.2.6", default-features = false }
subtle = { version = "1.0.0", default-features = false }
seckey = { version = "0.9.1", default-features = false }

[features]
default = [ "safe_api" ]
safe_api = [ "rand" ]

[dev-dependencies]
hex = "0.3.2"
ring = "0.13.2"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3

[badges]
travis-ci = { repository = "brycx/orion" }
codecov = { repository = "brycx/orion" }
maintenance = { status = "actively-developed" }
